import { Food } from './app/shared/models/food';



export const sample_foods:Food[]=[
    {
        id: '1',
        name: 'vegetables pizza',
        price:  50,
        cookTime:'40-50',
        favorite: false,
        origins: ['italy'],
        stars:  4.0,
        imageUrl: 'assets/pizza.jpg',
        tags: ['FastFood','pizza','Lunch'],
    },
    {
        id:'2',
        name:'vegetables burger',
        price:20,
        cookTime:'30-40',
        favorite:false,
        origins:['america'],
        stars:4.0,
        imageUrl:'assets/burger.jpg',
        tags:['FastFood','burger','Lunch'],
    },
    {
        id:'3',
        name:'vegetables chanakhi',
        price:30,
        cookTime:'40-60',
        favorite:false,
        origins:['china'],
        stars:4.0,
        imageUrl:'assets/chanakhi.jpg',
        tags:['FastFood','chanakhi','breakfast'],
    },
    {
        id:'4',
        name:'nonveg chicken',
        price:80,
        cookTime:'40-80',
        favorite:false,
        origins:['india'],
        stars:4.0,
        imageUrl:'assets/chicken leg piece.jpg',
        tags:['FastFood','chicken','Lunch'],
    },
    {
        id:'5',
        name:'lobio',
        price:30,
        cookTime:'20-30',
        favorite: false,
        origins:['india'],
        stars:4.0,
        imageUrl:'assets/lobio.jpg',
        tags:['FastFood','lobio'],
    },
    {
        id:'6',
        name:'nuddles',
        price:20,
        cookTime:'10-20',
        favorite:false,
        origins:['china'],
        stars:4.0,
        imageUrl:'assets/nuddles.jpg',
        tags:['FastFood','nuddle','Lunch'],
    },
    {
        id:'7',
        name:'bread strawbery',
        price:40,
        cookTime:'10-30',
        favorite:false,
        origins:['japan'],
        stars:4.0,
        imageUrl:'assets/bread strawbery.jpg',
        tags:['bread strawbery','Lunch'],
    },
    {
        id:'8',
        name:'fish fry',
        price:60,
        cookTime:'30-40',
        favorite:false,
        origins:['india'],
        stars:4.0,
        imageUrl:'assets/fish fry.jpg',
        tags:['fish fry','Lunch'],
    },
    {
        id:'9',
        name:'Rice',
        price:30,
        cookTime:'10-20',
        favorite:false,
        origins:['india'],
        stars:4.0,
        imageUrl:'assets/Rice.jpg',
        tags:['Rice','Dinner'],
    },
]